version: '3.8'
 
services:
  ecoappetite-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json
    environment:
      - SPRING_PROFILES_ACTIVE=default
    restart: unless-stopped